apiVersion: apps/v1
kind: Deployment
metadata:
  name: smcapstone
  labels:
    app: smcapstone
spec:
  selector:
    matchLabels:
      app: smcapstone
  replicas: 3
  template:
    metadata:
      labels:
        app: smcapstone
    spec:
      containers:
      - name: app
        image: 9894034584/smcapstone
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
